### ISSUE TITLE
Uncaught Error: Class 'Boolxy\Trendyol\Enums\DateQueryType' not found

### ISSUE THREAD

**Issue by garsamba** [boolxy/trendyol#11]
öncelikle kütüphane için çok teşekkürler,
ufaktan kullanmaya başladım ancak ürün filtreleme böyle bir hata veriyor anlamadım.

`Fatal error: Uncaught Error: Class 'Boolxy\Trendyol\Enums\DateQueryType' not found in C:\xampp\htdocs\boolxy\index.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\boolxy\index.php on line 17`

**Comment by sezaiozarslan** [comment]
Rica ederim. DataQueryType -> DateQueryType olarak yeniden isimlendirildi. Lütfen güncel versiyonu kullanınız.

**Comment by garsamba** [comment]
> Rica ederim. DataQueryType -> DateQueryType olarak yeniden isimlendirildi. Lütfen güncel versiyonu kullanınız.

composer ile daha yeni indirdim kütüphaneyi ama?
ve satırda `->dateQueryType(DateQueryType::create(DateQueryType::LAST_MODIFIED_DATE))` yazıyor zaten hocam.

**Comment by garsamba** [comment]
> Rica ederim. DataQueryType -> DateQueryType olarak yeniden isimlendirildi. Lütfen güncel versiyonu kullanınız.

varmı bir gelişme hocam?

**Comment by sezaiozarslan** [comment]
Aldığınız hatada DateQueryType'ın olmadığı söyleniyor. Eski versiyonlarında olan DataQueryType -> DateQueryType olarak yeniden isimlendirildi. Proje kodlarınızı gözden geçirebilirsiniz.

**Comment by garsamba** [comment]
> DateQueryType

hocam doğru diyorsunuz ancak DateQueryType 3 adet dosyasa mevcut
trendyol/src/Builders/GetProductsRequestBuilder.php
trendyol/src/Requests/ProductService/GetProducts.php
trendyol/src\/Enums/DataQueryType.php

DataQueryType olarak dosyaları arattığımda bir sonuç çıkmıyor ve şuan dosyaları tekrar indirip deniyorum yine aynı hata

`Fatal error: Uncaught Error: Class 'Boolxy\Trendyol\Enums\DateQueryType' not found in C:\xampp\htdocs\boolxy2\index.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\boolxy2\index.php on line 17`

**Comment by garsamba** [comment]
> Aldığınız hatada DateQueryType'ın olmadığı söyleniyor. Eski versiyonlarında olan DataQueryType -> DateQueryType olarak yeniden isimlendirildi. Proje kodlarınızı gözden geçirebilirsiniz.

tamam şimdi buldum trendyol/src/Enums/ klasörünün içinde dosya adı DataQueryType.php olarak adlandırılmış, sanırım onu düzenlemeyi unutmuşsunuz hocam.

**Comment by sezaiozarslan** [comment]
Teşekkür ederim. Güncelliyorum.
