### ISSUE TITLE
Claim Service için page ve size seçenekleri?

### ISSUE THREAD

**Issue by garsamba** [boolxy/trendyol#13]
öncelikle kütüphane için teşekkürler,
iadeleri çekme sınıfı için page ve size seçenekleri yok sanırım, olursa çok iyi olur teşekkürler..

**Comment by garsamba** [comment]
> öncelikle kütüphane için teşekkürler,
> iadeleri çekme sınıfı için page ve size seçenekleri yok sanırım, olursa çok iyi olur teşekkürler..

product dosyalarından sınıfları kopyalayıp kendim eklemeler yaparak oluşturdum teşekkürler..

**Comment by sezaiozarslan** [comment]
Rica ederim. Pull request ile kütüphane gelişimine katkı sağlayabilirsiniz. Bilgi için teşekkürler.
