### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by gneral** [boolxy/trendyol#14]
Merhaba, PHP hangi sürümünde tam olarak çalışmaktadır. 

**Kullandığım version 7.3.23:**

> local3398@localserver:~/public_html/xfiles$ php -v
> PHP 7.3.23-1+focal (cli) (built: Oct  1 2020 16:41:09) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.23-1+focal, Copyright (c) 1999-2018, by Zend Technologies

**Aldığım hata:**

> local3398@localserver:~/public_html/xfiles$ composer require boolxy/trendyol
> 
> 
>   [InvalidArgumentException]
>   Package boolxy/trendyol has a PHP requirement incompatible with your PHP ve
>   rsion, PHP extensions and Composer version

**Comment by garsamba** [comment]
> Merhaba, PHP hangi sürümünde tam olarak çalışmaktadır.
> 
> **Kullandığım version 7.3.23:**
> 
> > local3398@localserver:~/public_html/xfiles$ php -v
> > PHP 7.3.23-1+focal (cli) (built: Oct  1 2020 16:41:09) ( NTS )
> > Copyright (c) 1997-2018 The PHP Group
> > Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
> > with Zend OPcache v7.3.23-1+focal, Copyright (c) 1999-2018, by Zend Technologies
> 
> **Aldığım hata:**
> 
> > local3398@localserver:~/public_html/xfiles$ composer require boolxy/trendyol
> > [InvalidArgumentException]
> > Package boolxy/trendyol has a PHP requirement incompatible with your PHP ve
> > rsion, PHP extensions and Composer version

7.4ün altında çalışmıyor hocam.
