### ISSUE TITLE
Where can Ii get user and password?

### ISSUE THREAD

**Issue by aliqasemzadeh** [boolxy/trendyol#17]
Hi
Where can I get user and password?

**Comment by aliqasemzadeh** [comment]
@sezaiozarslan

**Comment by sezaiozarslan** [comment]
https://partner.trendyol.com/onboarding/satici-formu

**Comment by aliqasemzadeh** [comment]
@sezaiozarslan 
I need all product list in trendyol?
Can I use this package/?
