### ISSUE TITLE
startDate problemi

### ISSUE THREAD

**Issue by eness** [boolxy/trendyol#3]
Merhabalar,

OrderService üzerinden startDate vererek siparişleri çekmeye çalışınca sıfır sipariş dönüyor. Örneğin 1 Mart'tan itibaren siparişleri getirince, hergün sipariş olmasına rağmen 0 sonuç dönüyor. startDate silip sadece endDate vererek işlem yapınca çalışıyor ve sonuç dönüyor.

Muhtemelen API tarafında bir problem gibi görünüyor. Bu konuda bilginiz var mıdır?

**Comment by sezaiozarslan** [comment]
Merhaba Enes Bey,

Kütüphanenin yapısına göre startDate ve endDate kullanımı arasında bir fark yoktur. Sorunun API tarafında olduğu yönündeki izleminize katılıyorum. Fakat elimde bir trendyol partner hesabı olmadığı için test ederek aynı sorunu gözlemleyemiyorum. Umarım sizin bu mesajınız vesilesiyle Trendyol'da çalışan meslektaşlarımız sorunu farkedip, gerekli düzenlemeyi yaparlar.
