### ISSUE TITLE
composer çalışmıyor

### ISSUE THREAD

**Issue by garsamba** [boolxy/trendyol#5]
merhaba hocam, composer ile kütüphane inmemektedir bilginize..

**Comment by garsamba** [comment]
> merhaba hocam, composer ile kütüphane inmemektedir bilginize..

tamamdır php sürümüm düşük olduğu için indirtmiyormuş..

**Comment by sezaiozarslan** [comment]
Merhabalar,

PHP 7.4 ve üzerinde çalıştırabilirsiniz.
