### ISSUE TITLE
RequestManager hatası

### ISSUE THREAD

**Issue by garsamba** [boolxy/trendyol#6]
denemek için çalıştırdığımda adığım hata aşağıdaki gibidir. sorun nedir acaba.

`Parse error: syntax error, unexpected 'RequestManager' (T_STRING), expecting variable (T_VARIABLE) in Trendyol.php on line 12`

**Comment by sezaiozarslan** [comment]
Kullandığınız PHP sürümüyle ilgili olabilir. 7.4 veya üzeri olmalı.

**Comment by garsamba** [comment]
cpanel daha 7.4 sürümüne geçmediki, ne yapacaz şimdi :)
