### ISSUE TITLE
Type: GuzzleHttp\Exception\ConnectException

### ISSUE THREAD

**Issue by copernix** [boolxy/trendyol#7]
PHP Version 7.4.11

An uncaught Exception was encountered
Type: GuzzleHttp\Exception\ConnectException

Message: cURL error 6: Could not resolve host: product-categories (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Filename: /home/testhost/app1/application/trendyol/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
Line Number: 200
--
Hem local denemelerimde hemde sunucu üzerinden denemelerimde böyle bir hata alıyorum. 
Teşekkürler...

**Comment by sezaiozarslan** [comment]
Sorun tespiti yapabilmek adına Trendyol'dan test kullanıcısı talebinde bulundum. Gelişmelere göre tekrar dönüş yapacağım. Geri bildiriminiz için teşekkürler.

**Comment by copernix** [comment]
hocam sorun yok hata bende...
Kod içerisindede endpoint'i set eden bir fonksiyon görmediğim için trendyolun endpoint'i default olarak tanımlı olduğunu düşünmüştüm. ancak endpointi getenv ile çağırdığını geçte olsa farkettim. environment file henüz oluşturmadığım için putenv ile set edince tabi sorun kalmadı.

putenv("TRENDYOL_BASE_URI=https://api.trendyol.com/sapigw/");
